version: 0.2

env:
    variables:
        env: "BUILD_ENV"

batch:
    fast-fail: true
    # build-list:
    # build-matrix:
    # build-graph:

phases:
    install:
        on-failure: ABORT
        commands:
            - yarn
            - yarn test
            - echo "Zipping build artifacts"
            - zip -rq build.zip *
        finally:
            - echo "Install phase completed"
    # pre_build:
    #   run-as: Linux-user-name
    #   on-failure: ABORT | CONTINUE
    #   commands:
    #     - command
    #     - command
    #   finally:
    #     - command
    #     - command
    #   # steps:
    # build:
    #   run-as: Linux-user-name
    #   on-failure: ABORT | CONTINUE
    #   commands:
    #     - command
    #     - command
#   post_build:
#       commands:
#         -
#   # steps:
#     run-as: Linux-user-name
#     on-failure: ABORT | CONTINUE
#     commands:
#       - command
#       - command
#     finally:
#       - command
#       - command
#     # steps:
# reports:
#   report-group-name-or-arn:
#     files:
#       - location
#       - location
#     base-directory: location
#     discard-paths: no | yes
#     file-format: report-format
artifacts:
    files:
        - build.zip
    name: "BuildOutput"
#   name: artifact-name
#   discard-paths: no | yes
#   base-directory: location
#   exclude-paths: excluded paths
#   enable-symlinks: no | yes
#   s3-prefix: prefix
#   secondary-artifacts:
#     artifactIdentifier:
#       files:
#         - location
#         - location
#       name: secondary-artifact-name
#       discard-paths: no | yes
#       base-directory: location
#     artifactIdentifier:
#       files:
#         - location
#         - location
#       discard-paths: no | yes
#       base-directory: location
# cache:
#   paths:
#     - path
#     - path
